const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const report={checks:[],errors:[],overflows:[]};
const out=path.resolve('.impeccable/review');fs.mkdirSync(out,{recursive:true});
const check=(label,condition)=>{assert.ok(condition,label);report.checks.push(label);};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url());});
 await page.goto('http://127.0.0.1:4173');await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:path.join(out,'landing-desktop.png')});
 check('Credential-free buyer and seller entry',await page.locator('[data-action="enter"]').count()===2);
 await page.locator('[data-action="enter"][data-role="buyer"]').click();
 check('First buyer entry starts guided walkthrough',await page.locator('.tour').count()===1);
 for(let i=0;i<12&&await page.locator('[data-action="tournext"]').count();i++)await page.locator('[data-action="tournext"]').click();
 check('Walkthrough ends without creating a fictitious order',await page.locator('.order-block').count()===0);
 const nav=async(view)=>page.locator(`.sidebar [data-action="nav"][data-view="${view}"]`).click();
 await nav('home');check('24 product catalogue',await page.locator('.product').count()===24);
 await page.locator('#search').fill('sage');check('Product search narrows catalogue',await page.locator('.product').count()>=2&&await page.locator('.product').count()<24);
 await page.locator('#search').fill('');await page.locator('[data-action="filter"][data-category="Cushion covers"]').click();check('Category has six cushion products',await page.locator('.product').count()===6);
 await page.locator('[data-action="filter"][data-category="All products"]').click();
 await page.locator('[data-action="product"][data-id="0"]').click();await page.locator('[data-action="customproduct"]').click();
 check('Product-to-custom-request draft is populated',await page.locator('[name="name"]').inputValue()==='Sage cotton bath towel · my specification');
 await nav('requests');await page.locator('[data-action="compare"][data-id="REQ-101"]').click();
 check('Factory full-cost model matches ₹19,565 rounding',await page.locator('.quote').first().innerText().then(t=>t.includes('₹19,565')));
 await page.locator('#credit-required').check();check('Credit dependency blocks two prepaid quotes',await page.locator('.quote button:disabled').count()===2);
 await page.locator('#credit-required').uncheck();
 await page.locator('[data-action="selectquote"][data-quote="Q-101"]').click();check('Bulk order requires sample approval',await page.locator('[data-action="sample"]').count()===1&&await page.locator('[data-action="placequote"]').count()===0);
 await page.locator('[data-action="sample"]').click();for(const checkbox of await page.locator('#sample-form input').all())await checkbox.check();await page.locator('#sample-form button[type="submit"]').click();
 await page.locator('[data-action="placequote"]').click();check('Buyer creates a simulated order',await page.locator('.order-block').count()===1);
 await page.locator('[data-action="switch"]').click();await page.locator('[data-action="tourstop"]').first().click();await nav('orders');
 for(let i=0;i<3;i++)await page.locator('[data-action="advanceorder"]').click();check('Seller dispatch updates shared order',await page.locator('.order-block').innerText().then(t=>t.includes('Dispatched')));
 await page.locator('[data-action="switch"]').click();await nav('orders');await page.locator('[data-action="receive"]').click();for(const checkbox of await page.locator('#receive-form input').all())await checkbox.check();await page.locator('#receive-form button[type="submit"]').click();
 check('Buyer receipt completes shared milestone',await page.locator('.order-block .badge').first().innerText()==='Received');
 await page.locator('[data-action="issue"]').click();await page.locator('[name="note"]').fill('Two units have stitching defects in this demo.');await page.locator('#issue-form button[type="submit"]').click();check('Discrepancy recorded without a guaranteed refund',await page.locator('.notice.amber').innerText().then(t=>t.includes('Pending review')));
 await page.locator('[data-action="reorder"]').click();check('Received purchase builds a repeat basket',await page.locator('.item-row').count()===1);
 await nav('plans');await page.locator('[data-action="plan"][data-plan="monthly"]').click();await page.locator('[data-action="activateplan"]').click();await nav('cart');check('Monthly plan covers procurement fee on next job',await page.locator('.receipt').innerText().then(t=>t.includes('₹0')));
 await nav('requests');await page.locator('[data-action="nav"][data-view="newrequest"]').click();await page.locator('[name="name"]').fill('Demo mustard kitchen towels');await page.locator('[name="category"]').selectOption('Kitchen linen');await page.locator('[name="baseline"]').fill('0');await page.locator('#request-form button[type="submit"]').click();
 check('Buyer publishes request into shared state',await page.locator('.request-row h3').first().innerText()==='Demo mustard kitchen towels');
 await page.locator('[data-action="switch"]').click();await nav('feed');check('New buyer request reaches seller feed',await page.locator('.demand-card').first().innerText().then(t=>t.includes('Demo mustard kitchen towels')));
 await page.locator('.demand-card [data-action="quoteform"]').first().click();await page.locator('#quote-form button[type="submit"]').click();check('Supplier quote appears in quote workspace',await page.locator('.request-row').count()>=2);
 await page.locator('[data-action="buyercompare"]').first().click();check('A submitted quote reaches buyer comparison',await page.locator('.quote').count()>=1);check('Missing baseline does not fabricate savings',await page.locator('.quote-grid').innerText().then(t=>t.includes('Add your current cost')));
 await page.locator('[data-action="switch"]').click();await nav('inventory');const before=await page.locator('.inventory-row').count();await page.locator('[data-action="listing"]').first().click();await page.locator('#listing-form [name="name"]').fill('Demo new natural towel');await page.locator('#listing-form button[type="submit"]').click();check('Supplier can add a stock listing',await page.locator('.inventory-row').count()===before+1);
 await page.screenshot({path:path.join(out,'seller-desktop.png')});
 await page.locator('[data-action="switch"]').click();await nav('home');await page.screenshot({path:path.join(out,'desktop.png')});
 await page.reload();await page.locator('[data-action="enter"][data-role="buyer"]').click();check('Orders survive reload',await page.evaluate(()=>JSON.parse(localStorage.getItem('meesho-merchant-demo-v1')).orders.length)===1);
 await page.setViewportSize({width:390,height:844});
 const mnav=async(view)=>page.locator(`.mobile-nav [data-action="nav"][data-view="${view}"]`).click();
 for(const next of ['home','requests','cart','plans','orders']){await mnav(next);check('Mobile '+next+' has no document overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await mnav('home');await page.screenshot({path:path.join(out,'mobile.png')});
 await mnav('requests');await page.locator('[data-action="compare"]').first().click();check('Phone comparison fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'comparison-mobile.png')});
 await page.locator('[data-action="switch"]').click();await page.locator('.mobile-nav [data-view="feed"]').click();check('Phone seller feed fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'seller-mobile.png')});
 await page.setViewportSize({width:320,height:740});await page.locator('.mobile-nav [data-view="inventory"]').click();check('Small-phone stock workspace fits viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('[data-action="demohelp"]').click();await page.locator('[data-action="resetconfirm"]').click();await page.locator('[data-action="reset"]').click();check('Reset restores role entry and default data',await page.locator('[data-action="enter"]').count()===2&&await page.evaluate(()=>JSON.parse(localStorage.getItem('meesho-merchant-demo-v1')).orders.length)===0);
 check('No JavaScript or missing-resource errors',report.errors.length===0);
 await browser.close();fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
})().catch(e=>{report.errors.push(e.stack);fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(report,null,2));console.error(e);process.exit(1);});
