const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const checks=[];const check=(label,ok)=>{assert.ok(ok,label);checks.push(label)};
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/');
const captures=path.resolve('.impeccable/review');fs.mkdirSync(captures,{recursive:true});
const geometry=()=>p.evaluate(()=>{const t=tourTarget().getBoundingClientRect(),g=document.querySelector('.tour').getBoundingClientRect(),r=document.querySelector('.tour-spotlight').getBoundingClientRect();return {visible:t.width>0&&r.height>=Math.min(t.height,30),overlap:Math.max(0,Math.min(t.right,g.right)-Math.max(t.left,g.left))*Math.max(0,Math.min(t.bottom,g.bottom)-Math.max(t.top,g.top)),guideFits:g.bottom<=innerHeight&&g.top>=66};});
await p.locator('[data-role="buyer"]').click();
for(let i=0;i<7;i++){await p.waitForTimeout(80);const g=await geometry();check('Desktop buyer step '+(i+1)+' spotlights a visible target',g.visible&&g.guideFits);check('Desktop buyer step '+(i+1)+' guide leaves target visible',g.overlap===0);if(i===2)await p.screenshot({path:path.join(captures,'quantity-tour-desktop.png')});await p.locator('[data-action="tournext"]').click();}
await p.locator('.sidebar [data-view="home"]').click();await p.locator('[data-action="product"][data-id="0"]').click();const slider=p.locator('.quantity-slider');await slider.fill('100');check('100 towel units apply ₹87.30 to every unit',await p.locator('.selected-unit').innerText()==='₹87.3'&&await p.locator('.selected-goods').innerText()==='₹8,730');await p.locator('[data-action="tierqty"][data-qty="400"]').click();check('Clicking a price break synchronises slider and costs',await slider.inputValue()==='400'&&await p.locator('.selected-unit').innerText()==='₹82.8'&&await p.locator('.selected-goods').innerText()==='₹33,120');check('Desktop product dialog has no horizontal overflow',await p.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await p.screenshot({path:path.join(captures,'quantity-product-desktop.png')});await p.locator('[data-action="close"]').click();await p.locator('.sidebar [data-view="cart"]').click();await p.locator('.quantity-slider').fill('100');check('Basket live goods use the selected tier',await p.locator('[data-basket-total="goods"]').innerText()==='₹8,730');check('Basket live freight and payable update together',await p.locator('[data-basket-total="freight"]').innerText()==='₹300'&&await p.locator('[data-basket-total="total"]').innerText()==='₹9,329');await p.locator('.quantity-slider').focus();await p.keyboard.press('ArrowRight');check('Slider supports keyboard quantity changes',await p.locator('.quantity-slider').inputValue()==='101');await p.locator('.quantity-slider').fill('50');check('Minimum quantity restores the base price',await p.locator('.selected-unit').innerText()==='₹90');await p.locator('[data-action="checkoutcart"]').click();check('Checkout preserves the current tier total',await p.locator('.modal .total').innerText().then(t=>t.includes('₹5,099')));await p.locator('[data-action="placecart"]').click();check('Order stores the priced basket total',await p.evaluate(()=>state.orders[0].goods===4500&&state.orders[0].payable===5099));
await p.locator('[data-action="switch"]').click();for(let i=0;i<6;i++){await p.waitForTimeout(80);const g=await geometry();check('Desktop seller step '+(i+1)+' has visible spotlight',g.visible&&g.guideFits);await p.locator('[data-action="tournext"]').click();}await p.locator('.sidebar [data-view="inventory"]').click();await p.locator('[data-action="listing"][data-id="0"]').click();await p.locator('[name="discount2"]').fill('5');await p.locator('#listing-form button[type="submit"]').click();await p.locator('[data-action="switch"]').click();await p.locator('.sidebar [data-view="home"]').click();await p.locator('[data-action="product"][data-id="0"]').click();await p.locator('.quantity-slider').fill('100');check('Seller-edited 5% tier reaches buyer pricing',await p.locator('.selected-unit').innerText()==='₹85.5');await p.locator('[data-action="addselected"]').click();await p.locator('.sidebar [data-view="cart"]').click();check('Selected product quantity survives add-to-basket',await p.locator('.quantity-slider').inputValue()==='100');await p.locator('.quantity-slider').fill('800');check('Slider cannot exceed available stock',await p.locator('.quantity-slider').getAttribute('max')==='800');
for(const size of [{width:390,height:844},{width:320,height:740}]){await p.setViewportSize(size);await p.locator('[data-action="tour"]').first().click();for(let i=0;i<7;i++){await p.waitForTimeout(80);const g=await geometry();check(size.width+'px buyer step '+(i+1)+' spotlight and guide fit',g.visible&&g.guideFits);if(i===2){check(size.width+'px price controls are not covered by guide',g.overlap===0);await p.screenshot({path:path.join(captures,'quantity-tour-'+size.width+'.png')});}await p.locator('[data-action="tournext"]').click();}check(size.width+'px page has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('[data-action="switch"]').click();await p.locator('[data-action="tour"]').first().click();for(let i=0;i<6;i++){await p.waitForTimeout(80);const g=await geometry();check(size.width+'px seller step '+(i+1)+' spotlight and guide fit',g.visible&&g.guideFits);await p.locator('[data-action="tournext"]').click();}await p.locator('[data-action="switch"]').click();}
check('No browser JavaScript errors',errors.length===0);await browser.close();fs.writeFileSync(path.join(__dirname,'quantity-results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));})().catch(e=>{console.error(e);process.exit(1)});
